///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace OurTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the OurTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b9504986-3722-4b61-99f8-647869456b0e")]
    public partial class OurTest1Repository : RepoGenBaseFolder
    {
        static OurTest1Repository instance = new OurTest1Repository();
        OurTest1RepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the OurTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("b9504986-3722-4b61-99f8-647869456b0e")]
        public static OurTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OurTest1Repository() 
            : base("OurTest1Repository", "/", null, 0, false, "b9504986-3722-4b61-99f8-647869456b0e", ".\\RepositoryImages\\OurTest1Repositoryb9504986.rximgres")
        {
            _rxmainframe = new OurTest1RepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b9504986-3722-4b61-99f8-647869456b0e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("befee5cb-31c6-464d-8bc9-d4426d18ffc7")]
        public virtual OurTest1RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class OurTest1RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("befee5cb-31c6-464d-8bc9-d4426d18ffc7")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            OurTest1RepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "befee5cb-31c6-464d-8bc9-d4426d18ffc7", "")
            {
                _rxtabintroduction = new OurTest1RepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("befee5cb-31c6-464d-8bc9-d4426d18ffc7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("befee5cb-31c6-464d-8bc9-d4426d18ffc7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("a26e5572-cf54-4fcd-b67a-cd8a516cc36d")]
            public virtual OurTest1RepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("a26e5572-cf54-4fcd-b67a-cd8a516cc36d")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "a26e5572-cf54-4fcd-b67a-cd8a516cc36d", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "0eeb9c61-da29-44f7-9e9c-2ff665310545");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "56a0ef0e-5513-448f-a692-5aa2b74798f0");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "ca63f25b-087f-4949-82e6-a5e8cf1d4504");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a26e5572-cf54-4fcd-b67a-cd8a516cc36d")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a26e5572-cf54-4fcd-b67a-cd8a516cc36d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("0eeb9c61-da29-44f7-9e9c-2ff665310545")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("0eeb9c61-da29-44f7-9e9c-2ff665310545")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("56a0ef0e-5513-448f-a692-5aa2b74798f0")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("56a0ef0e-5513-448f-a692-5aa2b74798f0")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("ca63f25b-087f-4949-82e6-a5e8cf1d4504")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("ca63f25b-087f-4949-82e6-a5e8cf1d4504")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
